print ("hello world")
name = input("Enter your name:")
print ("hello",name)
print (len(name))
print (type(name))
print (name[0])
print (name[-1])
print (name[0:3])
print (name[3:])
print (name[2:4])
print (name[:4])
print (name[:-3])
print (name[0:10:2])
print (name[::1])
print (name[::-1])
print (name[:])
print (name.lower())
print (name.upper ())
print (name.swapcase())
print (name.capitalize())
print (name.title())
print (a + a )   
print (a*5)
print (a + " " + "sachin")
a,b,c = 10,3,5.0
print (a//c) #a quotient c
print (a/b)
print (a%b)
print (a**b) #a power b
print (abs(b-a))
a = [1,5,8,2,3,5,9,7]
print (type(a))
print (a[0])
print a[-1]
